ALTER TABLE INVOICE_BILL ADD WITHOUTBILLAMOUNT VARCHAR(100) DEFAULT NULL;
ALTER TABLE INVOICE_BILL ADD REMAININGBILLAMOUNT VARCHAR(100) DEFAULT NULL;
ALTER TABLE INVOICE_BILL ADD REMAININGWITHOUTBILLAMOUNT VARCHAR(100) DEFAULT NULL;

ALTER TABLE INVOICE_BILL ADD PAIDBILLAMOUNT VARCHAR(100) DEFAULT NULL;
ALTER TABLE INVOICE_BILL ADD PAIDWITHOUTBILLAMOUNT VARCHAR(100) DEFAULT NULL;

ALTER TABLE INVOICE_BILL ADD PAIDSTATUS VARCHAR(100) DEFAULT NULL; --status for billing amount : CLEAR, PARTIAL_PAID, NOTHING_PAID
ALTER TABLE INVOICE_BILL ADD WPAIDSTATUS VARCHAR(100) DEFAULT NULL;--status for without bill paid status --CLEAR, PARTIAL_PAID, NOTHING_PAID

ALTER TABLE INVOICE_BILL ADD GRNUMBER VARCHAR(100) DEFAULT NULL; ---BILTY NUMBER

ALTER TABLE INVOICE_BILL ADD COL1NAME VARCHAR(100) DEFAULT NULL;
ALTER TABLE INVOICE_BILL ADD COL1VAL VARCHAR(100) DEFAULT NULL;
ALTER TABLE INVOICE_BILL ADD COL1OPERATOR VARCHAR(100) DEFAULT NULL; -- +, -, /, *

ALTER TABLE INVOICE_BILL ADD COL2NAME VARCHAR(100) DEFAULT NULL; 
ALTER TABLE INVOICE_BILL ADD COL2VAL VARCHAR(100) DEFAULT NULL; 
ALTER TABLE INVOICE_BILL ADD COL2OPERATOR VARCHAR(100) DEFAULT NULL; -- +, -, /, *

