UPDATE INVOICE_BILL SET PAIDWITHOUTBILLAMOUNT = WITHOUTBILLAMOUNT WHERE PAIDWITHOUTBILLAMOUNT <>TO_NUMBER(WITHOUTBILLAMOUNT) 
AND REMAININGWITHOUTBILLAMOUNT = 0 AND WPAIDSTATUS = 'ALL_CLEAR';

SELECT INVOICENUM, WITHOUTBILLAMOUNT, PAIDWITHOUTBILLAMOUNT, WPAIDSTATUS FROM INVOICE_BILL WHERE 
PAIDWITHOUTBILLAMOUNT <>TO_NUMBER(WITHOUTBILLAMOUNT) AND REMAININGWITHOUTBILLAMOUNT = 0 AND WPAIDSTATUS = 'ALL_CLEAR';

UPDATE OPENING_BALANCE_INFO SET RECEIVEDOPENINGBALANCEAMOUNT = OPENINGBALANCEAMOUNT WHERE STATUS = 'ALL_CLEAR'
AND REMAININGOPENINGBALANCEAMOUNT = 0 and TO_NUMBER(OPENINGBALANCEAMOUNT) <> RECEIVEDOPENINGBALANCEAMOUNT;
 
SELECT * FROM "PUBLIC"."OPENING_BALANCE_INFO" WHERE STATUS = 'ALL_CLEAR'
AND REMAININGOPENINGBALANCEAMOUNT = 0 and TO_NUMBER(OPENINGBALANCEAMOUNT) <> RECEIVEDOPENINGBALANCEAMOUNT;
 
COMMIT;