CREATE TABLE STATECITYINFO (
	ID 		INTEGER PRIMARY KEY,
	CITY 		VARCHAR(100) DEFAULT NULL,
	STATE		VARCHAR(100) DEFAULT NULL,
	STATECODE	VARCHAR(100) DEFAULT NULL,
	ABBREVIATIONS VARCHAR(100) DEFAULT NULL,
	CREATEDDATE		TIMESTAMP,
	LASTUPDATED		TIMESTAMP,
	ISENABLE		BOOLEAN DEFAULT TRUE
);